"""
Small Streamlit module for adding spindle/NREM microarchitecture outputs to the
EMG burst QC app.

Usage inside emg_burst_interactive_QC_app.py:

    from spindle_app_module import render_spindle_dashboard, render_spindle_context_for_event

    spindle_events_path = st.sidebar.text_input("Spindle event table", "")
    spindle_metrics_path = st.sidebar.text_input("Spindle mouse/week metrics", "")

    ... inside Live metrics dashboard, after metrics are computed:
        render_spindle_dashboard(spindle_metrics_path, metrics)

    ... inside selected event metadata area:
        render_spindle_context_for_event(spindle_events_path, row)

This module does not detect spindles. It only loads the CSVs generated by
spindle_pipeline.py.
"""

from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
from scipy import stats


@st.cache_data(show_spinner=False)
def load_spindle_csv(path: str) -> pd.DataFrame:
    path = Path(path)
    if not path.exists() or not str(path):
        return pd.DataFrame()
    return pd.read_csv(path)


def _numeric_cols(df: pd.DataFrame, prefix_or_contains=None) -> list[str]:
    cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cols = [c for c in cols if c not in ["week", "mouse_id", "segment_id", "qc_event_id"]]
    if prefix_or_contains:
        cols = [c for c in cols if any(s in c for s in prefix_or_contains)]
    return cols


def _plot_group_week_progression(df: pd.DataFrame, metric: str, title: str | None = None):
    fig, ax = plt.subplots(figsize=(8.8, 5.0))
    data = df.copy()
    data["week"] = pd.to_numeric(data["week"], errors="coerce")
    data[metric] = pd.to_numeric(data[metric], errors="coerce")
    data = data.dropna(subset=["week", metric])

    for group, g in data.groupby("group"):
        g = g.sort_values("week")
        # Thin mouse lines if repeated.
        for mouse_id, m in g.groupby("mouse_id"):
            m = m.sort_values("week")
            if len(m) > 1:
                ax.plot(m["week"], m[metric], linewidth=0.8, alpha=0.35)
            ax.scatter(m["week"], m[metric], s=48, alpha=0.8, label=str(group) if mouse_id == list(g["mouse_id"].unique())[0] else None)
            for _, r in m.iterrows():
                ax.text(r["week"] + 0.05, r[metric], str(int(r["mouse_id"])), fontsize=8, va="center")

        summary = g.groupby("week")[metric].agg(["mean", "sem"]).reset_index()
        ax.errorbar(summary["week"], summary["mean"], yerr=summary["sem"], linewidth=2.0, marker="o", capsize=3)

    ax.set_xlabel("Week")
    ax.set_ylabel(metric)
    ax.set_title(title or metric)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(title="Group", fontsize=8)
    fig.tight_layout()
    return fig


def _plot_correlation(df: pd.DataFrame, x: str, y: str):
    sub = df[["group", "week", "mouse_id", x, y]].copy()
    sub[x] = pd.to_numeric(sub[x], errors="coerce")
    sub[y] = pd.to_numeric(sub[y], errors="coerce")
    sub = sub.dropna(subset=[x, y])

    fig, ax = plt.subplots(figsize=(6.2, 5.0))
    for group, g in sub.groupby("group"):
        ax.scatter(g[x], g[y], s=52, label=group, alpha=0.85)
        for _, r in g.iterrows():
            ax.text(r[x], r[y], f" M{int(r['mouse_id'])} W{int(r['week'])}", fontsize=7, va="center")

    rho = np.nan
    pval = np.nan
    if len(sub) >= 4:
        rho, pval = stats.spearmanr(sub[x], sub[y], nan_policy="omit")

    ax.set_xlabel(x)
    ax.set_ylabel(y)
    ax.set_title(f"Spearman rho={rho:.2f}, p={pval:.3f}" if np.isfinite(rho) else "Not enough points")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(fontsize=8)
    fig.tight_layout()

    stats_row = pd.DataFrame([{
        "x": x,
        "y": y,
        "n": len(sub),
        "spearman_rho": rho,
        "spearman_p": pval,
    }])
    return fig, stats_row


def render_spindle_dashboard(spindle_metrics_path: str, rbd_metrics: pd.DataFrame | None = None):
    with st.expander("Spindle / NREM microarchitecture", expanded=False):
        if not spindle_metrics_path:
            st.info("Add a spindle mouse/week metrics CSV path in the sidebar.")
            return

        sp = load_spindle_csv(spindle_metrics_path)
        if len(sp) == 0:
            st.warning("Could not load spindle mouse/week metrics table.")
            return

        st.caption("Spindle metrics are computed offline by spindle_pipeline.py and summarized at mouse/week level.")
        st.dataframe(sp.head(200).round(3), use_container_width=True)

        spindle_metric_options = [
            c for c in _numeric_cols(sp, prefix_or_contains=["spindle", "NREM"])
            if c in sp.columns
        ]
        default_metric = "spindle_density_per_NREM_min" if "spindle_density_per_NREM_min" in spindle_metric_options else spindle_metric_options[0]
        metric = st.selectbox("Spindle metric", spindle_metric_options, index=spindle_metric_options.index(default_metric))
        fig = _plot_group_week_progression(sp, metric, title=f"Spindle metric across genotype/week: {metric}")
        st.pyplot(fig)
        plt.close(fig)

        if rbd_metrics is not None and len(rbd_metrics):
            st.markdown("#### Correlate spindles with RBD/EMG metrics")
            merge_keys = ["group", "week", "mouse_id"]
            rbd = rbd_metrics.copy()
            for df in [sp, rbd]:
                for c in ["week", "mouse_id"]:
                    if c in df.columns:
                        df[c] = pd.to_numeric(df[c], errors="coerce").astype("Int64")
                if "group" in df.columns:
                    df["group"] = df["group"].astype(str)
            merged = rbd.merge(sp, on=merge_keys, how="inner", suffixes=("", "_spindle"))
            st.write(f"Merged mouse/week rows: **{len(merged)}**")

            candidate_rbd_metrics = [
                "QC_possible_RBD_like_per_EEGonly_REM_min",
                "QC_possible_or_transition_per_EEGonly_REM_min",
                "REM_relevant_EMG_episodes_per_EEGonly_REM_min",
                "primary_RBDlike_EMG_episodes_per_EEGonly_REM_min",
                "REM_fragmentation_index_bouts_per_REM_min",
                "percent_EEGonly_REM_epochs_with_QC_possible_RBD_like",
                "mean_delta_REM_REM_relevant",
                "mean_rem_wake_dissociation_REM_relevant",
                "mean_rbd_dissociation_score_REM_relevant",
            ]
            candidate_rbd_metrics = [c for c in candidate_rbd_metrics if c in merged.columns]
            if candidate_rbd_metrics:
                c1, c2 = st.columns(2)
                with c1:
                    x = st.selectbox("X: spindle metric", spindle_metric_options, index=spindle_metric_options.index(default_metric))
                with c2:
                    y = st.selectbox("Y: RBD/EMG metric", candidate_rbd_metrics)
                fig2, stat = _plot_correlation(merged, x, y)
                st.pyplot(fig2)
                plt.close(fig2)
                st.dataframe(stat.round(4), use_container_width=True)

                st.download_button(
                    "Download merged RBD + spindle mouse/week table",
                    data=merged.to_csv(index=False),
                    file_name="mouse_week_metrics_with_spindles.csv",
                    mime="text/csv",
                )
            else:
                st.info("No recognized RBD/EMG metric columns were found in the current metrics table.")


def render_spindle_context_for_event(spindle_events_path: str, event_row, window_sec: float = 60.0):
    if not spindle_events_path:
        return
    sp = load_spindle_csv(spindle_events_path)
    if len(sp) == 0:
        return

    required = ["group", "week", "mouse_id", "segment_id", "start_sec", "end_sec"]
    if not all(c in sp.columns for c in required):
        return

    try:
        group = str(event_row.get("group"))
        week = int(event_row.get("week"))
        mouse_id = int(event_row.get("mouse_id"))
        segment_id = int(event_row.get("segment_id"))
        event_start = float(event_row.get("start_sec"))
        event_end = float(event_row.get("end_sec"))
        event_mid = 0.5 * (event_start + event_end)
    except Exception:
        return

    sub = sp[
        (sp["group"].astype(str) == group)
        & (pd.to_numeric(sp["week"], errors="coerce").astype("Int64") == week)
        & (pd.to_numeric(sp["mouse_id"], errors="coerce").astype("Int64") == mouse_id)
        & (pd.to_numeric(sp["segment_id"], errors="coerce").astype("Int64") == segment_id)
    ].copy()
    if len(sub) == 0:
        return
    sub["spindle_mid_sec"] = 0.5 * (pd.to_numeric(sub["start_sec"], errors="coerce") + pd.to_numeric(sub["end_sec"], errors="coerce"))
    sub["distance_to_selected_event_sec"] = sub["spindle_mid_sec"] - event_mid
    nearby = sub[sub["distance_to_selected_event_sec"].abs() <= window_sec].copy().sort_values("distance_to_selected_event_sec")

    with st.expander(f"Nearby spindles ±{window_sec:.0f} s", expanded=False):
        st.metric("Spindles nearby", len(nearby))
        if len(nearby):
            show_cols = [
                "spindle_id", "start_sec", "end_sec", "duration_sec",
                "distance_to_selected_event_sec", "peak_sigma_z", "centFreq",
                "peak2peak", "time_to_nrem_end_sec", "next_state_after_NREM",
            ]
            show_cols = [c for c in show_cols if c in nearby.columns]
            st.dataframe(nearby[show_cols].round(3), use_container_width=True)

# =============================================================================
# Spindle detection QC plot viewer
# =============================================================================

@st.cache_data(show_spinner=False)
def load_spindle_qc_index(qc_index_path: str) -> pd.DataFrame:
    path = Path(qc_index_path)
    if not path.exists() or not str(path):
        return pd.DataFrame()
    return pd.read_csv(path)


def render_spindle_qc_plot_viewer(qc_index_path: str):
    """
    Display cached spindle QC PNGs generated by spindle_qc_plots.py.

    Add in the main app sidebar:
        spindle_qc_index_path = st.sidebar.text_input(
            "Spindle QC plot index",
            "Data/prepared_data/manifests/spindle_detection/qc_plots/spindle_qc_plot_index.csv",
        )

    Then call somewhere in the app:
        render_spindle_qc_plot_viewer(spindle_qc_index_path)
    """
    with st.expander("Spindle detection QC plots", expanded=False):
        if not qc_index_path:
            st.info("Add a spindle QC plot index CSV path in the sidebar.")
            return

        idx = load_spindle_qc_index(qc_index_path)
        if len(idx) == 0:
            st.warning("Could not load spindle_qc_plot_index.csv. Generate it with spindle_qc_plots.py first.")
            st.code(
                "python Code/spindle_qc_plots.py \\\n"
                "  --spindle-events Data/prepared_data/manifests/spindle_detection/spindle_events.csv \\\n"
                "  --config Data/prepared_data/manifests/spindle_detection/spindle_detector_config.json \\\n"
                "  --out-dir Data/prepared_data/manifests/spindle_detection/qc_plots"
            )
            return

        st.caption(
            "These are cached raw-signal QC plots around detected spindles. "
            "Gold spans are nearby detected spindles; the red span is the selected spindle."
        )

        c1, c2, c3 = st.columns(3)
        with c1:
            groups = sorted(idx["group"].dropna().astype(str).unique()) if "group" in idx.columns else []
            selected_groups = st.multiselect("QC plot group", groups, default=groups)
        with c2:
            weeks = sorted(pd.to_numeric(idx["week"], errors="coerce").dropna().astype(int).unique()) if "week" in idx.columns else []
            selected_weeks = st.multiselect("QC plot week", weeks, default=weeks)
        with c3:
            sort_options = [c for c in ["qc_plot_order", "peak_sigma_z", "duration_sec", "distance_to_nearest_transition_sec", "centFreq"] if c in idx.columns]
            sort_col = st.selectbox("Sort QC plots by", sort_options, index=0 if sort_options else None)

        view = idx.copy()
        if selected_groups and "group" in view.columns:
            view = view[view["group"].astype(str).isin(selected_groups)]
        if selected_weeks and "week" in view.columns:
            view = view[pd.to_numeric(view["week"], errors="coerce").astype("Int64").isin(selected_weeks)]
        if sort_col:
            view = view.sort_values(sort_col, ascending=(sort_col == "qc_plot_order"))

        if len(view) == 0:
            st.info("No QC plots in the current filter.")
            return

        labels = []
        for _, r in view.iterrows():
            labels.append(
                f"{r.get('qc_plot_order', '')} | {r.get('spindle_id', '')} | "
                f"{r.get('group', '')} W{r.get('week', '')} M{r.get('mouse_id', '')} seg{r.get('segment_id', '')} | "
                f"peak z={float(r.get('peak_sigma_z', np.nan)):.2f} | "
                f"dur={float(r.get('duration_sec', np.nan)):.2f}s | "
                f"next={r.get('next_state_after_NREM', '')}"
            )

        selected_label = st.selectbox("Select spindle QC plot", labels)
        selected_i = labels.index(selected_label)
        selected = view.iloc[selected_i]

        plot_path = Path(str(selected.get("qc_plot_path", "")))
        if not plot_path.exists():
            # If index moved with project folder, try relative to index parent.
            alt = Path(qc_index_path).parent / str(selected.get("qc_plot_file", ""))
            if alt.exists():
                plot_path = alt

        meta_cols = [
            "spindle_id", "group", "week", "mouse_id", "segment_id",
            "start_sec", "end_sec", "duration_sec", "peak_sigma_z", "mean_sigma_z",
            "centFreq", "peak2peak", "noCycle", "symmetry",
            "state_at_event", "next_state_after_NREM", "distance_to_nearest_transition_sec",
            "is_pre_transition_60s", "is_pre_NREM_to_Wake_60s", "is_pre_NREM_to_REM_60s",
        ]
        meta_cols = [c for c in meta_cols if c in selected.index]
        st.dataframe(pd.DataFrame(selected[meta_cols]).T, use_container_width=True)

        if plot_path.exists():
            st.image(str(plot_path), use_container_width=True)
        else:
            st.error("QC plot image not found.")
            st.code(str(selected.get("qc_plot_path", "")))

        st.download_button(
            "Download current QC plot index subset",
            data=view.to_csv(index=False),
            file_name="spindle_qc_plot_index_filtered.csv",
            mime="text/csv",
        )
